version: '3.8'

x-svc-default: &default_svc
  restart: on-failure
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
  networks:
    - massive-net
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "1"

services:

  mysql:
    <<: *default_svc
    hostname: mysql
    container_name: mysql-5
    image: mysql:5
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: passwor
    command:
      - mysqld
      - --explicit_defaults_for_timestamp
      - --character-set-server=utf8mb4
      - --skip-character-set-client-handshake
      - --collation-server=utf8mb4_unicode_ci
      - --skip-name-resolve
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

  massive-batch:
    <<: *default_svc
    hostname: massive-batch
    container_name: massive-batch
    image: com.github.eltonsandre/massive-batch:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $HOME/data:/data
    environment:
      - SERVER_PORT=80
      - MASSIVE_DATA_INPUT=/data/input
      - MASSIVE_DATA_OUTPUT=/data/output
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      - JAVA_OPTS=-Xms64m -Xmx128m -Dfile.encoding=UTF-8 -Duser.Timezone=America/Sao_Paulo -Duser.country=BR -Duser.language=pt
      - SPRING_DATASOURCE_SCHEMA=org/springframework/batch/core/schema-drop-mysql.sql,org/springframework/batch/core/schema-mysql.sql
    depends_on:
      - mysql


networks:
  massive-net:
    name: massive-net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.15.0/24